WITH CUSTOMERREVENUE AS (
    SELECT C.CUSTOMERID,
           CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
           COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
           SUM(OI.QUANTITY * OI.UNITPRICE) AS REVENUE
    FROM SNOWFLAKE_LEARNING_SCHEMA.CUSTOMERS C
    JOIN SNOWFLAKE_LEARNING_SCHEMA.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
    JOIN SNOWFLAKE_LEARNING_SCHEMA.ORDERITEMS OI ON O.ORDERID = OI.ORDERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY REVENUE DESC
)
SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT, REVENUE 
FROM CUSTOMERREVENUE